#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long B, long long G){
    if (B > G) {
        cout << "Bat" << endl;
    } else {
        cout << "Glove" << endl;
    }
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long B;
    std::scanf("%lld", &B);
    long long G;
    std::scanf("%lld", &G);
    solve(B, G);
    return 0;
}
