#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, long long K, long long S_X, long long S_Y, std::vector<long long> X, std::vector<long long> Y){

}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long K;
    std::scanf("%lld", &K);
    long long S_X;
    std::scanf("%lld", &S_X);
    long long S_Y;
    std::scanf("%lld", &S_Y);
    std::vector<long long> X(N);
    std::vector<long long> Y(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &X[i]);
        std::scanf("%lld", &Y[i]);
    }
    solve(N, K, S_X, S_Y, std::move(X), std::move(Y));
    return 0;
}
