#include <bits/stdc++.h>
using namespace std;
using ll = long long;

ll floor(ll x, ll m) {
    ll r = (x % m + m) % m;
    return (x - r) / m;
}

void solve(long long A, long long M, long long L, long long R){
    ll distL = L - A;
    ll distR = R - A;
    ll mink = floor(distL - 1, M);
    ll maxk = floor(distR, M);
    cout << maxk - mink << endl;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    std::scanf("%lld", &A);
    long long M;
    std::scanf("%lld", &M);
    long long L;
    std::scanf("%lld", &L);
    long long R;
    std::scanf("%lld", &R);
    solve(A, M, L, R);
    return 0;
}
