#include <bits/stdc++.h>
using namespace std;
using ll = long long;


// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    // Failed to predict input format
    return 0;
}
